### ISSUE TITLE
Network Connection for Venodr Package

### ISSUE THREAD

**Issue by qiayuanl** [jspricke/ros-deb-builder-action#53] opened 2024-09-01 19:19 UTC
Hi, thank you for sharing this package, this is super useful.

When I try on package like [onnxruntime_vendor](https://github.com/ms-iot/ros_msft_onnx/blob/foxy/onnxruntime_vendor/package.xml) or [blasfeo_catkin](https://github.com/leggedrobotics/ocs2/tree/main/ocs2_sqp/blasfeo_catkin), I got some error like:

```
  CMake Error at CMakeLists.txt:27 (file):
    file DOWNLOAD HASH mismatch
  
      for file: [/<<BUILDDIR>>package/obj-x86_64-linux-gnu/onnxruntime.nuget]
        expected hash: [c9c2ba5c594c92c1e426e9c53f9909e8851a41c99f48f8a369e082f8047d521b236f2fbb943e73975cbb45bd9957f20139c25959e50e1679dca9eeac08f73b31]
          actual hash: [cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e]
               status: [6;"Couldn't resolve host name"]
```

This is because these packages try to download files before building, and the sandbox does not seem to provide such a network interface. What's the correct way to deal with these packages?

**Comment by jspricke** [comment] 2024-09-01 19:26
Duplicate of #38.

**Closed by jspricke** 2024-09-01 19:26 UTC
